spring:
    datasource:
        url: jdbc:mysql://<host>:3306/<database_name>?createDatabaseIfNotExist=true
        username: admin
        password: admin123
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate.ddl-auto: create
        show-sql: true
        generate-ddl: false
  # Producer properties
    kafka:
      bootstrap-servers: <host kafka>:9092
      group-id: group_id
topic:
  name:
    producer: ed-topic-1 
    consumer: ed-topic-1 
# Common Kafka Properties
auto:
  create:
    topics:
      enable: true

#AWS properties
cloud:
    aws:
        region:
            static: us-east-1
        stack:
            auto: false
        credentials:
            accessKey: <access_key> 
            secretKey: <secret_key>

application:
    bucket:
        name: <bucket_name> 

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
 
baseUrl: http://prod-gateway-api.local:5555/v1 #gateway service url
